language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - gem install sass
  - npm install -g gulp
script: gulp test -b Phantom
services: mongodb
